/**
 * Copy the shared SQLite schema from the contracts into the desktop bundle.
 *
 * `core/src/contracts/db.sql` is the single source of truth (owned by the
 * architect); the Tauri app cannot read files from `core/` at runtime, so the
 * SQL is embedded at build time. `npm run build` executes this first; if the
 * contract file is missing the script fails loudly instead of shipping a stale
 * schema.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const source = path.resolve(here, '../../core/src/contracts/db.sql');
const targetDir = path.resolve(here, '../src/db');
const target = path.join(targetDir, 'schema.generated.ts');

const sql = await readFile(source, 'utf8').catch(() => {
  console.error(`[sync:schema] missing shared schema at ${source}`);
  process.exit(1);
});

if (!/CREATE TABLE meta/.test(sql) || !/CREATE VIRTUAL TABLE ayah_search/.test(sql)) {
  console.error('[sync:schema] unexpected schema contents — refusing to embed');
  process.exit(1);
}

const body = `// GENERATED by scripts/syncSchema.mjs — do not edit.
// Source of truth: core/src/contracts/db.sql (shared contracts).
export const SCHEMA_SQL = ${JSON.stringify(sql)};
`;

await mkdir(targetDir, { recursive: true });
const existing = await readFile(target, 'utf8').catch(() => null);
if (existing !== body) {
  await writeFile(target, body, 'utf8');
  console.log(`[sync:schema] updated ${path.relative(process.cwd(), target)}`);
} else {
  console.log('[sync:schema] already current');
}
