import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';
import { createContentMiddleware } from './dev/contentMiddleware.mjs';

// `content/` is generated by tools/content and lives outside this workspace.
// In browser-dev mode the app must read the *same* pack files the packaged app
// reads, so the dev server serves the repo `content/` directory at /content.
const contentRoot = fileURLToPath(new URL('../content', import.meta.url));

export default defineConfig({
  root: fileURLToPath(new URL('.', import.meta.url)),
  base: './',
  plugins: [react(), createContentMiddleware(contentRoot)],
  clearScreen: false,
  server: {
    port: 5173,
    strictPort: true,
    fs: { allow: ['..'] },
  },
  build: {
    target: 'es2022',
    outDir: 'dist',
    emptyOutDir: true,
  },
});
